{
 "title": "Zookeeper Overview",
 "description": "For more information, please visit https://github.com/zifter/helm-charts/tree/main/charts/zookeeper-exporter",
 "tags": [
  "zookeeper",
  "prometheus"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "query": "prometheus" },
   { "name": "job", "query": { "query": "label_values(zk_up,job)" } },
   {
    "name": "instance",
    "query": {
     "query": "label_values(zk_up{job=~\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zk_up{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{ zk_host }}"
    }
   ]
  },
  {
   "title": "Is Leader",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "zk_server_leader{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{ zk_host }}"
    }
   ]
  },
  {
   "title": "Ephemerals Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zk_ephemerals_count{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{ zk_host }}"
    }
   ]
  },
  {
   "title": "Znode Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zk_znode_count{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{ zk_host }}"
    }
   ]
  },
  {
   "title": "Znode Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zk_znode_count{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{ zk_host }}"
    }
   ]
  },
  {
   "title": "ZK Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zk_version{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{ zk_host }} {{  version }}"
    }
   ]
  },
  {
   "title": "Pakages Sent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(zk_packets_sent{job=~\"$job\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{ zk_host }}"
    }
   ]
  },
  {
   "title": "Pakages Recieved",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(zk_packets_received{job=~\"$job\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{ zk_host }}"
    }
   ]
  },
  {
   "title": "Alive Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_num_alive_connections{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{ zk_host }}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_open_file_descriptor_count{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "open {{ zk_host }}"
    },
    {
     "expr": "zk_max_file_descriptor_count{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "max {{ zk_host }}"
    }
   ]
  },
  {
   "title": "Avg Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_avg_latency{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{ zk_host }}"
    }
   ]
  },
  {
   "title": "Min Latency",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zk_min_latency{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{ zk_host }}"
    }
   ]
  },
  {
   "title": "Max Latency",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zk_max_latency{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{ zk_host }}"
    }
   ]
  },
  {
   "title": "Outstanding Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_outstanding_requests{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{ zk_host }}"
    }
   ]
  },
  {
   "title": "Approx Data Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "zk_approximate_data_size{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{ zk_host }}"
    }
   ]
  }
 ]
}