{
 "title": "Agones Controller API Server Requests",
 "tags": [
  "agones",
  "controller",
  "server"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Prometheus", "query": "prometheus" },
   {
    "name": "CustomResourceDefinition",
    "label": "CRD",
    "query": "fleets, gameservers, gameserversets, gameserverallocations"
   },
   {
    "name": "Subresource",
    "query": "\"status\", \"scale\", \"\""
   },
   { "name": "Verb", "query": { "query": "" } }
  ]
 },
 "panels": [
  {
   "title": "Main Resource Request Count per Second",
   "type": "graph",
   "description": "API Server Main Resource Request count for Fleet/Gameserver/Gameserverset",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count{resource=~\"[[CustomResourceDefinition]]\",verb!~\"WATCH|LIST\",subresource=~\"\"}[5m])) by (resource,verb)",
     "legendFormat": "{{verb}} {{resource}}"
    }
   ]
  },
  {
   "title": "Subresource Request Count per Second",
   "type": "graph",
   "description": "API Server Subresource Request count for Fleet/Gameserver/Gameserverset",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count{resource=~\"[[CustomResourceDefinition]]\",verb!~\"WATCH|LIST\",subresource!~\"\"}[5m])) by (resource,subresource,verb)",
     "legendFormat": "{{verb}} {{resource}} {{subresource}}"
    }
   ]
  },
  {
   "title": "Request Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count{code=\"409\",resource=~\"[[CustomResourceDefinition]]\", subresource=~[[Subresource]]}[5m])) by (code, resource, subresource)",
     "legendFormat": "{{resource}} {{subresource}} {{code}}"
    }
   ]
  },
  {
   "title": "Update Conflicts",
   "type": "graph",
   "description": "409 error on Update of Resources",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count{code=\"409\",resource=~\"[[CustomResourceDefinition]]\",subresource=[[Subresource]]}[5m])) by (code, resource, subresource)",
     "legendFormat": "{{resource}} {{subresource}}"
    }
   ]
  },
  {
   "title": "Request Latency 50%",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(apiserver_request_latencies_summary{resource=~\"[[CustomResourceDefinition]]\", verb=~\"[[Verb]]\", quantile=\"0.5\"}/1000) by (resource, subresource, verb)",
     "legendFormat": "{{verb}} {{resource}} {{subresource}}"
    }
   ]
  },
  {
   "title": "Request Latency 90%",
   "type": "graph",
   "description": "Request Latency, 90% quantile with verb selector",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(apiserver_request_latencies_summary{resource=~\"[[CustomResourceDefinition]]\", verb=~\"[[Verb]]\", quantile=\"0.9\"}/1000) by (resource, subresource, verb)",
     "legendFormat": "{{verb}} {{resource}} {{subresource}}"
    }
   ]
  },
  {
   "title": "Request Latency 99%",
   "type": "graph",
   "description": "Request Latency, 99% quantile with verb selector",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(apiserver_request_latencies_summary{resource=~\"[[CustomResourceDefinition]]\", verb=~\"[[Verb]]\", quantile=\"0.99\"}/1000) by (resource, subresource, verb)",
     "legendFormat": "{{verb}} {{resource}} {{subresource}}"
    }
   ]
  }
 ]
}