{
 "title": "Agones  Allocations",
 "description": "Agones gameserver allocations",
 "tags": [
  "agones",
  "nodes",
  "controller",
  "gameservers",
  "allocations",
  "fleets"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Prometheus", "query": "prometheus" },
   {
    "name": "fleet",
    "query": {
     "query": "label_values(agones_gameservers_count, fleet_name)"
    }
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Average latency",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(agones_gameserver_allocations_duration_seconds_sum[$interval]))\n/\nsum(rate(agones_gameserver_allocations_duration_seconds_count[$interval]))"
    }
   ]
  },
  {
   "title": "Allocation Errors rate",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "format": "reqps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(agones_gameserver_allocations_duration_seconds_count{status!=\"Allocated\"}[$interval]))"
    }
   ]
  },
  {
   "title": "GameServer Allocations Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5,sum(rate(agones_gameserver_allocations_duration_seconds_bucket{fleet_name=~\"$fleet\"}[$interval])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.9,sum(rate(agones_gameserver_allocations_duration_seconds_bucket{fleet_name=~\"$fleet\"}[$interval])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.99,sum(rate(agones_gameserver_allocations_duration_seconds_bucket{fleet_name=~\"$fleet\"}[$interval])) by (le))",
     "legendFormat": "99%"
    }
   ]
  },
  {
   "title": "GameServer allocations rate by status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(agones_gameserver_allocations_duration_seconds_count{fleet_name=~\"$fleet\"}[$interval])) by (status)",
     "legendFormat": "{{status}}"
    },
    {},
    {}
   ]
  },
  {
   "title": "GameServer allocations rate by fleet",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(agones_gameserver_allocations_duration_seconds_count{fleet_name=~\"$fleet\",}[$interval])) by (fleet_name)",
     "legendFormat": "{{fleet_name}}"
    }
   ]
  },
  {
   "title": "Allocations rate per node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(agones_gameserver_allocations_duration_seconds_count{status=\"Allocated\"}[$interval])) by (node_name)",
     "legendFormat": "{{node_name}}"
    }
   ]
  }
 ]
}