{
 "title": "Agones Autoscalers",
 "tags": [
  "agones",
  "autoscaler"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Prometheus", "query": "prometheus" },
   { "name": "name", "query": { "query": "" } }
  ]
 },
 "panels": [
  {
   "title": "Fleet % Allocated",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(label_replace(agones_fleets_replicas_count{type=\"allocated\"},\"fleet_name\",\"$1\",\"name\",\"(.*)\")  * on (fleet_name) group_left()  (agones_fleet_autoscalers_able_to_scale{name=\"$name\"}))\n\n/ on(name)\n\n(label_replace(agones_fleets_replicas_count{type=\"desired\"},\"fleet_name\",\"$1\",\"name\",\"(.*)\")  * on (fleet_name) group_left()  (agones_fleet_autoscalers_able_to_scale{name=\"$name\"}))"
    }
   ]
  },
  {
   "title": "Fleet % Ready",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(label_replace(agones_fleets_replicas_count{type=\"ready\"},\"fleet_name\",\"$1\",\"name\",\"(.*)\")  * on (fleet_name) group_left()  (agones_fleet_autoscalers_able_to_scale{name=\"$name\"}))\n\n/ on(name)\n\n(label_replace(agones_fleets_replicas_count{type=\"desired\"},\"fleet_name\",\"$1\",\"name\",\"(.*)\")  * on (fleet_name) group_left()  (agones_fleet_autoscalers_able_to_scale{name=\"$name\"}))"
    }
   ]
  },
  {
   "title": "Current Desired Scaling Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "(agones_fleet_autoscalers_desired_replicas_count{name=\"$name\"} - agones_fleet_autoscalers_current_replicas_count{name=\"$name\"})"
    }
   ]
  },
  {
   "title": "Autoscaler Current Desired Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "agones_fleet_autoscalers_desired_replicas_count{name=\"$name\"}"
    }
   ]
  },
  {
   "title": "Buffer Size Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "agones_fleet_autoscalers_buffer_size{name=\"$name\",type=\"count\"}"
    }
   ]
  },
  {
   "title": "Min buffer size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "agones_fleet_autoscalers_buffer_limits{name=\"$name\",type=\"min\"}"
    }
   ]
  },
  {
   "title": "Current Desired Scaling %",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 3 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(agones_fleet_autoscalers_desired_replicas_count{name=\"$name\"} - agones_fleet_autoscalers_current_replicas_count{name=\"$name\"})\n\n  / \n\nagones_fleet_autoscalers_current_replicas_count{name=\"$name\"} "
    }
   ]
  },
  {
   "title": "Autoscaler Current Replica Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "agones_fleet_autoscalers_current_replicas_count{name=\"$name\"}"
    }
   ]
  },
  {
   "title": "Buffer Size %",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "agones_fleet_autoscalers_buffer_size{name=\"$name\",type=\"percentage\"}"
    }
   ]
  },
  {
   "title": "Max buffer size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "agones_fleet_autoscalers_buffer_limits{name=\"$name\",type=\"max\"}"
    }
   ]
  },
  {
   "title": "Fleet Replicas",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "agones_fleet_autoscalers_current_replicas_count{name=\"$name\"}",
     "legendFormat": "fas current replicas"
    },
    {
     "expr": "agones_fleet_autoscalers_desired_replicas_count{name=\"$name\"}",
     "legendFormat": "fas desired replicate"
    },
    {
     "expr": "label_replace(agones_fleets_replicas_count{type=\"allocated\"},\"fleet_name\",\"$1\",\"name\",\"(.*)\")  * on (fleet_name) group_left()  (agones_fleet_autoscalers_able_to_scale{name=\"$name\"})",
     "legendFormat": "fleet allocated"
    },
    {
     "expr": "label_replace(agones_fleets_replicas_count{type=\"ready\"},\"fleet_name\",\"$1\",\"name\",\"(.*)\")  * on (fleet_name) group_left()  (agones_fleet_autoscalers_able_to_scale{name=\"$name\"})",
     "legendFormat": "fleet ready"
    },
    {
     "expr": "label_replace(agones_fleets_replicas_count{type=\"desired\"},\"fleet_name\",\"$1\",\"name\",\"(.*)\")  * on (fleet_name) group_left()  (agones_fleet_autoscalers_able_to_scale{name=\"$name\"})",
     "legendFormat": "fleet desired"
    },
    {
     "expr": "(agones_fleet_autoscalers_desired_replicas_count{name=\"$name\"} - agones_fleet_autoscalers_current_replicas_count{name=\"$name\"})",
     "legendFormat": "desired scaling"
    }
   ]
  },
  {
   "title": "Scaling Limited",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "agones_fleet_autoscalers_limited{name=\"$name\"}"
    }
   ]
  },
  {
   "title": "Able to scale",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "agones_fleet_autoscalers_able_to_scale{name=\"$name\"}"
    }
   ]
  }
 ]
}