{
 "title": "Agones Allocator Resource",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Allocators Open File Descriptor Count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(process_open_fds{app=\"agones\",kubernetes_pod_name=~\"agones-allocator-.*\"})"
    }
   ]
  },
  {
   "title": "Last Go GC",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "format": "dateTimeFromNow",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(go_memstats_last_gc_time_seconds{app=\"agones\",kubernetes_pod_name=~\"agones-allocator-.*\"} * 1000)"
    }
   ]
  },
  {
   "title": "Allocators Memory Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{app=\"agones\",kubernetes_pod_name=~\"agones-allocator-.*\"}) by (kubernetes_pod_name)",
     "legendFormat": "resident - {{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(process_virtual_memory_bytes{app=\"agones\",kubernetes_pod_name=~\"agones-allocator-.*\"})by (kubernetes_pod_name)",
     "legendFormat": "virtual - {{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(go_memstats_alloc_bytes{app=\"agones\",kubernetes_pod_name=~\"agones-allocator-.*\"})by (kubernetes_pod_name)",
     "legendFormat": "go alloc - {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Allocators Go Routines & Threads Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{app=\"agones\",kubernetes_pod_name=~\"agones-allocator.*\"}",
     "legendFormat": "go routines"
    },
    {
     "expr": "go_threads{app=\"agones\",kubernetes_pod_name=~\"agones-allocator.*\"}",
     "legendFormat": "threads"
    }
   ]
  },
  {
   "title": "Allocators CPU Used (% of core)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum (irate (process_cpu_seconds_total{app=\"agones\",kubernetes_pod_name=~\"agones-allocator-.*\"}[1m])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Average Go GC Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": " avg(rate(go_gc_duration_seconds_sum{app=\"agones\",kubernetes_pod_name=~\"agones-allocator-.*\"}[5m]) / rate(go_gc_duration_seconds_count{app=\"agones\",kubernetes_pod_name=~\"agones-allocator-.*\"}[5m]))",
     "legendFormat": "duration"
    }
   ]
  }
 ]
}