{
 "title": "Clickhouse Overview",
 "description": "For more information, please visit https://github.com/zifter/helm-charts/tree/main/charts/domain-exporter",
 "tags": [
  "clickhouse",
  "db",
  "prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Query",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(clickhouse_query_total[1m])"
    }
   ]
  },
  {
   "title": "Merge",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "clickhouse_merge", "legendFormat": "merge {{job}}" },
    {
     "expr": "rate(clickhouse_merged_rows_total[1m])",
     "legendFormat": "rate {{job}}"
    }
   ]
  },
  {
   "title": "Replication",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "clickhouse_replicated_checks" },
    { "expr": "clickhouse_replicated_fetch" },
    { "expr": "clickhouse_replicated_send" }
   ]
  },
  {
   "title": "ReadOnly replica",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 6, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(clickhouse_readonly_replica)"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "clickhouse_leader_replica", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Compressed Read Buffer",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(clickhouse_compressed_read_buffer_bytes_total[1m])",
     "legendFormat": "{{job}}"
    },
    {}
   ]
  },
  {
   "title": "Read/Write",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "clickhouse_read" },
    { "expr": "clickhouse_write" }
   ]
  },
  {
   "title": "Pool Tasks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "clickhouse_background_pool_task",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "clickhouse_tcp_connection", "legendFormat": "tcp {{instance}}" },
    { "expr": "clickhouse_http_connection", "legendFormat": "http {{instance}}" },
    {
     "expr": "clickhouse_interserver_connection",
     "legendFormat": "interserver"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "clickhouse_memory_tracking" }
   ]
  },
  {
   "title": "Cache rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(clickhouse_mark_cache_misses_total[5m])",
     "legendFormat": "misses {{job}}"
    },
    {
     "expr": "rate(clickhouse_mark_cache_hits_total[5m])",
     "legendFormat": "hits {{job}}"
    }
   ]
  }
 ]
}